services:
  dockerupdate-notif:
    image: docker:cli
    container_name: dockerupdate-notif
    restart: unless-stopped
    environment:
      - TELE_TOK=${TELE_TOK}
      - CHAT_ID=${CHAT_ID}
      - TZ=Africa/Cairo
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./scan.sh:/scan.sh
      - ./data:/data
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        # Initial install to ensure bash exists for the loop
        apk add --no-cache bash curl jq
        chmod +x /scan.sh
        
        # The Infinite Loop
        while true; do
          /bin/bash /scan.sh
          echo "Sleeping for 6 hours..."
          sleep 21600
        done
