services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:5.2.1@sha256:1fc3067c4e684a4139be2e17915a63e9355ccba91c954a330d33fcb033bf7e71
    labels:
      - "dash.description=Torrent client"
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Cairo
      - WEBUI_PORT=8080
    volumes:
      - ./config:/config
      - /data/assets:/data
    networks:
      - proxy
    ports:
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

networks:
  proxy:
    external: true
