services:
  pocket-id:
    image: ghcr.io/pocket-id/pocket-id:latest
    user: "1000:1000"
    container_name: pocket-id
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - ./data:/app/data
      - ${HOST_CERT_PATH}:/etc/ssl/certs/homeserver-ca.pem:ro
    environment:
      # First time setting up visit https://pocket.homeserver/setup
      - APP_URL=https://pocket.homeserver
      - TRUST_PROXY=true
      - ANALYTICS_DISABLED=true
      - VERSION_CHECK_DISABLED=true
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - SSL_CERT_FILE=/etc/ssl/certs/homeserver-ca.pem

networks:
  proxy:
    external: true
