services:
  jdownloader:
    image: jlesage/jdownloader-2:latest
    container_name: jdownloader
    environment:
      - MYJDOWNLOADER_EMAIL=${JD2_USER}
      - MYJDOWNLOADER_PASSWORD=${JD2_PASS}
      - MYJDOWNLOADER_DEVICE_NAME=Homeserver
      - JDOWNLOADER_HEADLESS=1 # 1 here means no GUI. Managing is through my.jdownloader.org
      - USER_ID=1000
      - GROUP_ID=1000
    volumes:
      - ./config:/config
      - /data/assets/downloads:/output:rw
      - /data/assets/downloads/watch:/output/watch:rw
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    external: true
