services:
  jdownloader:
    image: jlesage/jdownloader-2:v26.03.1@sha256:3d6cb102bd9bacff12ab1ca5136a38cb8f93d6595a7ccf5bce60aac4df138ebd
    container_name: jdownloader
    labels:
      - "dash.description=Download manager"
    environment:
      - MYJDOWNLOADER_EMAIL=${JD2_USER}
      - MYJDOWNLOADER_PASSWORD=${JD2_PASS}
      - MYJDOWNLOADER_DEVICE_NAME=Wonderland
      - JDOWNLOADER_HEADLESS=1 # 1 here means no GUI. Managing is through my.jdownloader.org
      - USER_ID=1000
      - GROUP_ID=1000
    volumes:
      - ./config:/config
      - /data/assets/downloads:/output:rw
      - /data/assets/downloads/watch:/output/watch:rw
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    external: true
