services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:2.35.1@sha256:1eef6716183c52abafe5405e7d6be8390248ecd59c7488c44af871757ac8fc4d
    container_name: audiobookshelf
    labels:
      - "dash.description=Audiobook and podcast server"
    networks:
      - proxy
    volumes:
      - ./config:/config
      - ./metadata:/metadata
      - /data/assets/syncthing/Backup/self-hosted/audiobookshelf:/config/backups
      - /data/assets/Media/Books:/audiobooks:rw
      - /data/assets/Media/Podcasts:/podcasts:rw
      - ${HOST_CERT_PATH}:/etc/ssl/certs/homeserver-ca.pem:ro
    environment:
      - TZ=Africa/Cairo
      - AUDIOBOOKSHELF_UID=1000
      - AUDIOBOOKSHELF_GID=1000
      - NODE_EXTRA_CA_CERTS=/etc/ssl/certs/homeserver-ca.pem
    restart: unless-stopped
networks:
  proxy:
    external: true
