services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - 127.0.0.1:5678:5678
    environment:
      # --- NETWORK CONFIG ---
      # To have Tailscale act as a webhook post-restore:
      # docker exec tailscaled tailscale serve reset
      # docker exec tailscaled tailscale funnel --bg --https=443 http://127.0.0.1:5678
      - WEBHOOK_URL=https://${TAILSCALE_DOMAIN}
      - GENERIC_TIMEZONE=Africa/Cairo
      # --- SECRETS ---
      # Variables can be added in a workflow like: {{ $env.MY_BOT_TOKEN }}, and choose 'Expression' instead of 'Fixed'
      - MY_BOT_TOKEN=${TELEGRAM_DANTE_TOKEN}
      - MY_2ND_BOT_TOKEN=${TELEGRAM_VERGIL_TOKEN}
      - CHAT_ID=${MY_TELEGRAM_CHAT_ID}
      - SONARR_API=${SON_API}
      - RADARR_API=${RAD_API}
      - QBIT_USER=${QBIT_USER}
      - QBIT_PASS=${QBIT_PASS}
      - PIHOLE_APP_PASS=${PIHOLE_PASS}
      - N8N_ENV_ALLOWLIST=*
      - N8N_BLOCK_ENV_ACCESS_IN_NODE=false
      # --- PRIVACY & LOGS ---
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_PERSONALIZATION_ENABLED=false
      - N8N_VERSION_NOTIFICATIONS_ENABLED=false
      # --- DATABASE MAINTENANCE ---
      # Keeps the database small and fast
      - EXECUTIONS_DATA_PRUNE=true
      - EXECUTIONS_DATA_MAX_AGE=24
      - DB_SQLITE_POOL_SIZE=10
      - EXECUTIONS_DATA_SAVE_ON_SUCCESS=none
      - EXECUTIONS_DATA_SAVE_ON_ERROR=all
      - EXECUTIONS_DATA_SAVE_ON_PROGRESS=false
      - EXECUTIONS_DATA_SAVE_MANUAL_EXECUTIONS=true
      # --- SECURITY ---
      - N8N_SECURE_COOKIE=false
      - NODES_EXCLUDE=[]
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      # --- PROCESS MANAGEMENT ---
      - N8N_RUNNERS_ENABLED=true
    volumes:
      - ./n8n_data:/home/node/.n8n
      - /data/assets/downloads:/downloads:rw
      - /data/assets/downloads/watch:/watch-folder:rw

networks:
  proxy:
    external: true
