services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    dns:
      - 1.1.1.1
    ports:
      # In case if port 53 is already in use. The issue is a `systemd-resolved` occupying the port. Just run:
      # sudo sed -i 's/#DNSStubListener=yes/DNSStubListener=no/' /etc/systemd/resolved.conf
      # sudo systemctl restart systemd-resolved
      - 53:53/tcp
      - 53:53/udp
    networks:
      - proxy
      - internal
    environment:
      - TZ=Africa/Cairo
      - WEBPASSWORD=${PASS}
      - ADDITIONAL_PACKAGES=python3 curl
      - CHECK_LOAD=false
      - FTLCONF_database_maxDBdays=7
      - PIHOLE_DNS_=unbound#5335
    volumes:
      - ./etc-pihole:/etc/pihole
      - ./etc-dnsmasq.d:/etc/dnsmasq.d
    restart: unless-stopped

networks:
  proxy:
    external: true
  internal:
    internal: true
