services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v1.8
    container_name: homepage
    init: true
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - 7575:3000
    volumes:
      - ./config:/app/config
      - ./config/images:/app/public/images
    environment:
      - PUID=1000
      - PGID=1000
      - LOG_LEVEL=info
      - HOMEPAGE_ALLOWED_HOSTS=*
networks: {}
