services:
  romm:
    image: rommapp/romm:4.8.1@sha256:2b7a1714b287f69b081ad2a63bb8c2fa673666a17b2f21322b580b0cd51cb266
    container_name: romm
    labels:
      - "dash.description=ROM manager and game library browser"
    restart: unless-stopped
    environment:
      - DB_HOST=romm-db
      - DB_NAME=romm
      - DB_USER=romm
      - DB_PASSWD=${DB_MYSQL_PASS}
      - ROMM_AUTH_SECRET_KEY=${ROMM_AUTH_KEY}
      - IGDB_CLIENT_ID=${IGDB_TWITCH_CLIENT_ID}
      - IGDB_CLIENT_SECRET=${IGDB_TWITCH_CLIENT_SECRET}
      - REDIS_HOST=romm-redis
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Cairo
      # OIDC support
      - OIDC_TLS_CACERTFILE=/etc/ssl/certs/homeserver-ca.pem
      - OIDC_ENABLED=true
      - OIDC_PROVIDER=pocket-id
      - OIDC_CLIENT_ID=${ROMM_CLIENT_ID}
      - OIDC_CLIENT_SECRET=${ROMM_CLIENT_SECRET}
      - OIDC_REDIRECT_URI=https://romm.wonder.lan/api/oauth/openid
      - OIDC_SERVER_APPLICATION_URL=https://pocket.wonder.lan
    volumes:
      - ${HOST_CERT_PATH}:/etc/ssl/certs/homeserver-ca.pem:ro
      - /data/assets/romm/resources:/romm/resources
      - ./config:/romm/config
      - ./assets:/romm/assets
      # the roms need to be in a folder called 'roms' inside each platform folder (e.g. romm/library/snes/roms)
      - /data/assets/romm/library:/romm/library
    networks:
      - proxy
      - internal
    depends_on:
      romm-db:
        condition: service_healthy
      romm-redis:
        condition: service_started
  romm-db:
    image: mariadb:11.8@sha256:be1ef4fe5f14589325c08a41c76334097ce66c86264b75e1d28342c742782a61
    container_name: romm-db
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=${MYSQL_PASS}
      - MARIADB_DATABASE=romm
      - MARIADB_USER=romm
      - MARIADB_PASSWORD=${DB_MYSQL_PASS}
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - internal
    healthcheck:
      test:
        - CMD
        - healthcheck.sh
        - --connect
        - --innodb_initialized
      start_period: 180s
      interval: 20s
      timeout: 5s
      retries: 10
  romm-redis:
    image: redis:8.8-alpine@sha256:09160599abd229764c0fb44cb6be640294e1d360a54b19985ab4843dcf2d90f1
    container_name: romm-redis
    restart: unless-stopped
    networks:
      - internal

networks:
  proxy:
    external: true
  internal:
    internal: true
