services:
  robot:
    build: .
    container_name: wifi-robot
    init: true
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env

networks:
  proxy:
    external: true

# USAGE:
# http://wifi-robot:5000/on - turns the Guest WiFi ON
# http://wifi-robot:5000/off - turns the Guest WiFi OFF
