services:
  robot:
    build: .
    container_name: wifi-robot
    init: true
    restart: unless-stopped
    ports:
      - "5050:5000"
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env

# USAGE:
# http://ip:5050/on - turns the Guest WiFi ON
# http://ip:5050/off - turns the Guest WiFi OFF
