services:
  diun:
    image: crazymax/diun:latest
    container_name: diun
    command: serve
    restart: unless-stopped
    environment:
      - TZ=Africa/Cairo
      - LOG_LEVEL=info
      - LOG_JSON=false
      - DIUN_WATCH_WORKERS=20
      - DIUN_WATCH_SCHEDULE=0 */6 * * *
      - DIUN_PROVIDERS_DOCKER=true
      - DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT=true
      - DIUN_NOTIF_TELEGRAM_TOKEN=${TELE_TOK}
      - DIUN_NOTIF_TELEGRAM_CHATIDS=${CHAT_ID}
      # Tell Diun to look at the proxy, not the socket file
      - DIUN_PROVIDERS_DOCKER_ENDPOINT=tcp://diun-socket-proxy:2375
    volumes:
      - ./data:/data
    depends_on:
      - diun-socket-proxy
    networks:
      - diun-net
  diun-socket-proxy:
    image: tecnativa/docker-socket-proxy
    container_name: diun-socket-proxy
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Read-only mount
    environment:
      - CONTAINERS=1 # Allow listing containers
      - IMAGES=1 # Allow inspecting images (Critical for Diun!)
    networks:
      - diun-net
networks:
  diun-net:
    driver: bridge
