services:
  scrutiny:
    container_name: scrutiny
    labels:
      - "dash.description=S.M.A.R.T. drive health monitoring"
    image: ghcr.io/starosdev/scrutiny:master-omnibus@sha256:8c09f958f4bbd0cfe68ee1396517420c33704226839186a04cdc5ec56381780e
    cap_add:
      - SYS_RAWIO
    privileged: true
    stop_grace_period: 2m
    networks:
      - proxy
    volumes:
      - /run/udev:/run/udev:ro
      - ./config:/opt/scrutiny/config
      - ./influxdb:/opt/scrutiny/influxdb
    environment:
      - TZ=Africa/Cairo
      - SCRUTINY_NOTIFY_URLS=${TELE_DANTE_TOKEN}
      - SCRUTINY_WEB_INFLUXDB_INIT_TIMEOUT=120s
      - SCRUTINY_ARGS=--log-level debug
      - S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0
    restart: unless-stopped

networks:
  proxy:
    external: true
