services:
  glances:
    image: nicolargo/glances:4.5.4@sha256:a11e836511ff83cd123b460c21bb4cf2795ac149ac7a18f9b01587bfcb5a5033
    container_name: glances
    labels:
      - "dash.description=Real-time system resource monitor"
    restart: unless-stopped
    pid: host
    networks:
      - proxy
    environment:
      # -w : Web Server mode (Default is port 61208)
      # -t 5 : Refresh every 5 seconds (Default is 2 or 3)
      - GLANCES_OPT=-w -t 5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  proxy:
    external: true
