services:
  tailscale:
    container_name: tailscaled
    image: tailscale/tailscale:v1.98.4@sha256:25cde9ad76020b0e29229136d0c38b5962e9a0e1774ffac9b0df68e4a37d6cf0
    hostname: Homeserver
    network_mode: host
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ./config:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    environment:
      # To generate a new key — if needed, go to https://login.tailscale.com/admin/settings/keys, then 'Generate auth key...', make sure to tick 'Reusable' and 'Tags' and select a tag, then Generate key
      # Make sure the tailscale ip of the server is added in DNS > Add nameserver > Custom > Save then tick 'Override DNS servers' 
      - TS_AUTHKEY=${AUTH_KEY}
      # Make sure that the 'Subnet routes' is active on the Tailscale Admin Console with the below
      - TS_EXTRA_ARGS=--advertise-routes=192.168.1.0/24
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_SOCKS5_SERVER=:1055
networks: {}
