services:
  borg-ui:
    image: ainullcode/borg-ui:latest
    container_name: borg-web-ui
    restart: unless-stopped
    ports:
      - "8093:8081"
    volumes:
      - borg_data:/data
      - borg_cache:/home/borg/.cache/borg
      # Mount directories you want to backup (REPLACE with your actual paths)
      - /srv/data/assets:/local/assets:ro
      - /srv/data/borg_backup:/home/borg_backup:rw
    environment:
      - TZ=Africa/Cairo
      - PUID=1000
      - PGID=1000

volumes:
  borg_data:
  borg_cache:
