services:
  uptime-kuma:
    image: louislam/uptime-kuma:next
    container_name: uptime-kuma
    user: "1000:1000"
    restart: unless-stopped
    networks:
      - proxy
      - internal
    volumes:
      - ./data:/app/data
    environment:
      # Add tcp://uptime-socket-proxy:2375 in 'Docker Hosts' from Kuma's Settings.
      - DOCKER_HOST=tcp://127.0.0.1:2375
    depends_on:
      - uptime-socket-proxy
  uptime-socket-proxy:
    image: tecnativa/docker-socket-proxy
    container_name: uptime-socket-proxy
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - CONTAINERS=1
    networks:
      - internal

networks:
  proxy:
    external: true
  internal:
    internal: true
