services:
  syncthing:
    image: syncthing/syncthing:2.1
    container_name: syncthing
    hostname: Homeserver
    networks:
      - proxy
    ports:
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    environment:
      - PUID=1000
      - PGID=1000
      - STGUIADDRESS=0.0.0.0:8384
    volumes:
      - ./config:/var/syncthing/config
      - /data:/data
    restart: unless-stopped

networks:
  proxy:
    external: true
