services:
  syncthing:
    image: syncthing/syncthing:latest
    container_name: syncthing
    hostname: Homeserver
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - STGUIADDRESS=0.0.0.0:8384
    volumes:
      - ./config:/var/syncthing/config
      - /srv/data:/srv/data
    restart: unless-stopped
networks: {}
