- Infrastructure:
    - Pi-hole:
        icon: pi-hole.png
        href: https://pihole.homeserver/admin
        description: DNS Filtering
        widget:
            type: pihole
            url: http://pihole:80
            version: 6
            key: {{HOMEPAGE_VAR_PI_API}}

    - Nginx Proxy Manager:
        icon: nginx-proxy-manager.png
        href: https://npm.homeserver
        description: Proxy Manager
        widget:
            type: npm
            url: http://192.168.1.109:81
            username: {{HOMEPAGE_VAR_NPM_USER}}
            password: {{HOMEPAGE_VAR_NPM_PASS}}

- Monitoring:
    - Uptime Kuma Status Page:
        icon: uptime-kuma.png
        href: https://kuma.homeserver/status/home
        widget:
            type: uptimekuma
            url: http://uptime-kuma:3001
            slug: home

    - Uptime Kuma:
        icon: uptime-kuma.png
        href: https://kuma.homeserver
        description: Uptime Monitoring

    - Scrutiny:
        icon: scrutiny.png
        href: https://scrutiny.homeserver
        description: Drive Health

    - Glances:
        icon: glances.png
        href: https://glances.homeserver
        description: Resource Monitor

- Admin:
    - Dockge:
        icon: dockge.png
        href: https://dockge.homeserver
        description: Container Manager

    - Borg Web UI:
        icon: borgmatic.png
        href: https://borg.homeserver
        description: Borg Backup web interface

    - n8n:
        icon: n8n.png
        href: https://n8n.homeserver
        description: Workflow Automation

    - Home Router:
        icon: router.png
        href: http://192.168.1.1
        description: Default Gateway

- Cloud:
    - Nextcloud:
        icon: nextcloud.png
        href: https://nextcloud.homeserver
        description: Files
        widget:
            type: nextcloud
            url: http://nextcloud:80
            username: {{HOMEPAGE_VAR_NEXTCLOUD_USER}}
            password: {{HOMEPAGE_VAR_NEXTCLOUD_APP_PASS}}

    - Paperless-ngx:
        icon: paperless-ngx.png
        href: https://paperless.homeserver
        description: Archives
        widget:
            type: paperlessngx
            url: http://paperless-ngx:8000
            key: {{HOMEPAGE_VAR_PAPERLESS_API}}

    - Syncthing:
        icon: syncthing.png
        href: https://syncthing.homeserver
        description: Sync

- Media & Entertainment:
    - RomM:
        icon: romm
        href: https://romm.homeserver
        description: ROM Manager
        widget:
            type: romm
            url: http://romm:8080

    - Jellyfin:
        icon: jellyfin.png
        href: https://jellyfin.homeserver
        description: Movies, Series & Music
        widget:
            type: jellyfin
            url: http://jellyfin:8096/
            key: {{HOMEPAGE_VAR_JELLYFIN_KEY}}
            enableBlocks: true
            enableNowPlaying: false
            showEpisodeNumber: true

    - Audiobookshelf:
        icon: audiobookshelf.png
        href: https://audiobooks.homeserver
        description: Books
        widget:
            type: audiobookshelf
            url: http://audiobookshelf:80/
            key: {{HOMEPAGE_VAR_AUDIOBOOKSHELF_API}}

- Downloads:
    - qBittorrent:
        icon: qbittorrent.png
        href: https://qbit.homeserver
        description: Torrents
        widget:
            type: qbittorrent
            url: http://qbittorrent:8080/
            username: {{HOMEPAGE_VAR_QBIT_USERNAME}}
            password: {{HOMEPAGE_VAR_QBIT_PASS}}

    - JDownloader 2:
        icon: jdownloader.png
        href: https://jd.homeserver
        description: Direct Downloads
        widget:
            type: jdownloader
            username: {{HOMEPAGE_VAR_JD2_USER}}
            password: {{HOMEPAGE_VAR_JD2_PASS}}
            client: jd@homeserver

- Arrs:
    - Radarr:
        icon: radarr.png
        href: https://radarr.homeserver
        description: Movies
        widget:
            type: radarr
            url: http://radarr:7878/
            key: {{HOMEPAGE_VAR_RADARR_KEY}}
            enableQueue: true

    - Sonarr:
        icon: sonarr.png
        href: https://sonarr.homeserver
        description: TV Shows
        widget:
            type: sonarr
            url: http://sonarr:8989/
            key: {{HOMEPAGE_VAR_SONARR_KEY}}
            enableQueue: true

    - Prowlarr:
        icon: prowlarr.png
        href: https://prowlarr.homeserver
        description: Indexers
        widget:
            type: prowlarr
            url: http://prowlarr:9696/
            key: {{HOMEPAGE_VAR_PROWLARR_KEY}}

    - Bazarr:
        icon: bazarr.png
        href: https://bazarr.homeserver
        description: Subtitles
        widget:
            type: bazarr
            url: http://bazarr:6767/
            key: {{HOMEPAGE_VAR_BAZARR_KEY}}

