services:
  dockge:
    image: louislam/dockge:1.5.0@sha256:335c6368b880ecc203236ed89e6e5232e0d6578e8ef5920e4a502390451502bf
    container_name: dockge
    labels:
      - "dash.description=Docker Compose stack manager UI"
      - "dash.notes=First stack to bring up on a fresh restore"
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      # This tells Dockge that your "stacks" live in /opt
      - /opt/stacks:/opt/stacks
    environment:
      # Tell Dockge where stacks are internally
      - DOCKGE_STACKS_DIR=/opt/stacks
networks:
  proxy:
    external: true
